# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='visitors',
            new_name='visitor',
        ),
    ]
