# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20170930_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name': 'visitor', 'verbose_name_plural': 'visitors'},
        ),
    ]
