# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20180201_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipeimage',
            old_name='recipe_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='recipetag',
            old_name='recipe_tag',
            new_name='tag',
        ),
    ]
