# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-04 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20180201_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeimage',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipetag',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='media/recipes/images/borsch.jpg', upload_to='media/recipes/images/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.CharField(choices=[('H', 'Горячее блюдо'), ('C', 'Холодное блюдо'), ('Salad', 'Салат'), ('Soup', 'Суп'), ('Bakery', 'Выпечка')], default=None, max_length=64),
        ),
        migrations.DeleteModel(
            name='RecipeImage',
        ),
        migrations.DeleteModel(
            name='RecipeTag',
        ),
    ]
