# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-05 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20180204_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.CharField(choices=[('Горячее блюдо', 'Горячее блюдо'), ('Холодное блюдо', 'Холодное блюдо'), ('Салат', 'Салат'), ('Суп', 'Суп'), ('Выпечка', 'Выпечка')], default=None, max_length=64),
        ),
    ]
