# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-05 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20180205_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='status',
            field=models.CharField(blank=True, choices=[('Свежее', 'Свежее'), ('Популярное', 'Популярное'), ('Лучшее', 'Лучшее')], default=None, max_length=64, null=True),
        ),
    ]
