# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-27 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_views_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.CharField(blank=True, choices=[('Свежее', 'Свежее'), ('Популярное', 'Популярное'), ('Лучшее', 'Лучшее'), ('Архив', 'Архив')], default=None, max_length=64, null=True),
        ),
    ]
