# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-27 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20180227_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_active',
        ),
    ]
