# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-11 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_remove_recipe_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
